import { generateSidebar } from 'vitepress-sidebar'

export default generateSidebar([
  {
    documentRootPath: '/ch01-python基础',
    scanStartPath: '',
    resolvePath: '/ch01-python基础/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
    excludeFolders: ['code'],
  },
  {
    documentRootPath: '/ch02-感知机',
    scanStartPath: '',
    resolvePath: '/ch02-感知机/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
    excludeFolders: ['code'],
  },
  {
    documentRootPath: '/ch03-神经网络',
    scanStartPath: '',
    resolvePath: '/ch03-神经网络/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
    excludeFolders: ['code'],
  },
  {
    documentRootPath: '/ch04-神经网络的学习',
    scanStartPath: '',
    resolvePath: '/ch04-神经网络的学习/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
    excludeFolders: ['code'],
  },
  {
    documentRootPath: '/ch05-误差反向传播法',
    scanStartPath: '',
    resolvePath: '/ch05-误差反向传播法/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
    excludeFolders: ['code'],
  },
  {
    documentRootPath: '/ch06-学习技巧',
    scanStartPath: '',
    resolvePath: '/ch06-学习技巧/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
    excludeFolders: ['code'],
  },
  {
    documentRootPath: '/ch07-卷积神经网络',
    scanStartPath: '',
    resolvePath: '/ch07-卷积神经网络/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
    excludeFolders: ['code'],
  },
  {
    documentRootPath: '/ch08-深度学习进阶',
    scanStartPath: '',
    resolvePath: '/ch08-深度学习进阶/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
    excludeFolders: ['code'],
  },
  {
    documentRootPath: '/ch09-循环神经网络',
    scanStartPath: '',
    resolvePath: '/ch09-循环神经网络/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
    excludeFolders: ['code'],
  },
  {
    documentRootPath: '/ch10-注意力机制',
    scanStartPath: '',
    resolvePath: '/ch10-注意力机制/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
    excludeFolders: ['code'],
  },
  {
    documentRootPath: '/ch11-计算机视觉进阶',
    scanStartPath: '',
    resolvePath: '/ch11-计算机视觉进阶/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
    excludeFolders: ['code'],
  },
  {
    documentRootPath: '/ch12-自然语言处理',
    scanStartPath: '',
    resolvePath: '/ch12-自然语言处理/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
    excludeFolders: ['code'],
  },
])
